export const environment = {
  GRAPHQL_URI: 'http://localhost:4001/',
  GRAPHQL_WS_URI: 'ws://localhost:4001/',
  REDIRECT_URI: 'http://localhost:5500/',
  CLIENT_ID: 'AXLwU3GZQDd7yAIUXIGFhptYJ5mgN6NA',
  CLIENT_AUTHORITY: 'dev-pb3zdwv3lfh86612.us.auth0.com',
  auth0ClientId: "AXLwU3GZQDd7yAIUXIGFhptYJ5mgN6NA",
  auth0ClientSecret: "qdfTj2W7wa0ndp5UPnkZ-THQc941FawlZghD9Bbv-O2bGX5cKckfON3vKPLWlzbB",
  AUTH0_DOMAIN:"dev-pb3zdwv3lfh86612.us.auth0.com",
  AUTH_TYPE: 'Auth0',
  NODE_ENV: "development",
  AUTOSAVE_DEBOUNCE_MS: 1200,
  SEARCH_DEBOUNCE_MS: 800,
  MIN_SEARCH_LENGTH: 3,
  production: false,
  APP_TITLE: 'Abstracts Portal',
};