export const environment = {"GRAPHQL_URI":"http://localhost:4002/",
    "GRAPHQL_WS_URI":"ws://localhost:4002/",
    "REDIRECT_URI":"http://localhost:4200/",
    "CLIENT_ID":"",
    "TENANT_ID":"",
    "CLIENT_AUTHORITY":"",
    "AUTH_TYPE":"MSAL","NODE_ENV":"development",
    "AUTOSAVE_DEBOUNCE_MS":1200,
    "SEARCH_DEBOUNCE_MS":800,
    "MIN_SEARCH_LENGTH":3,
    "MJ_CORE_SCHEMA_NAME":"__mj",
    "production":false,
    "APPLICATION_NAME":"CDP",
    "APPLICATION_INSTANCE":"DEV",
    "AUTH0_DOMAIN":"dev-pb3zdwv3lfh86612.us.auth0.com",
    "AUTH0_CLIENTID":"AXLwU3GZQDd7yAIUXIGFhptYJ5mgN6NA"
}